name: example
description: A theme manager for light, dark, and system themes. Change the theme dynamically and the selected theme will be persisted.
version: 1.0.0
homepage: https://github.com/matthewrice345/theme_manager

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  theme_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
