name: theme_manager
description: A theme manager for light, dark, and system themes. Change the theme dynamically and the selected theme will be persisted.
version: 2.0.3
homepage: https://github.com/matthewrice345/theme_manager

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  platform: ^3.1.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: